displayName=Drop History
author=markuskkramer
description=Tracks what KC you received each collection log item at. Hover any item in your collection log to see a full list.
tags=collection log,drop,kc,kill count,loot,tracker
plugins=com.drophistory.DropHistoryPlugin
build=standard
